version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"